services:
  - type: web
    name: websocket-server
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    webService:
      port: 8080
      healthCheckPath: /
      tls: true  # Automatically adds HTTPS (wss://)
    timeout: 300
